name: Publish Docker image

on:
  push:
    branches:
     - main
     - dev

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: iniciar sesion dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout code
        uses: actions/checkout@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permisos de ejecucion a gradlew
        run: chmod +x gradlew

      - name: Construir con Gradle dentro de Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          gradle:8.10.2-jdk21-alpine \
          ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservices:asigsolcamacamillero-image-${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:asigsolcamacamillero-image-${{ github.ref_name }}